language: java

rvm:
 - 2.2
 - jruby
 - rbx-2

deploy:
  provider: heroku
  api_key:
    secure: HNvxBbCoZyk7Gi1lsH7DHsTjUAp65cdec287K9XSL/ETogO+h0F0MfMnyOqPw5rWH6FYLu/kcF07YsLjDSVV3IFfcxqhrFSi1RDfjCWPsqEkLwn8c5zpiLyrwgKmrCrhk/5MowDdNzFVNr57pmC7SrLzIXIXoIsuFa/CaENHwTFR2FUOzXWgQu+jFs+2hCDr1h1gsvMgaEx89dX8ylj13/a2S/PZGLrLGTaLjoGgAyBcDGZYbkWrXahzzykW8grqURBR0J690RzL9SA2l66CfcsOnYQOonXG5//t5GfJ6CiIs78FUolNIb8k6TiA0sdQ0ZEHgBZPdOuS4QpzQaJ0IDWhtBdS/iMh99h4oWpWwpjKXyTuEZCWE0a1VDDd1Iz+LC2hsnxTd15B96MxhX+u8Q0n+rbVP1iZkby5/oI3HXexyZz3hiWSv2dFBZeYMfZUaIkXGF66dEylPBbr17yBkmamGTVInkMmPiZRWjO191px+KMW7eR8+Iy8tqewdxoO6PiWAMsP1IX+cva0cz2+6Gdi0zQBXiFEZ06kJdIENIT5nE3M8PGuaX2txC5CyjAK4jVQVfuDKpAg1HvJiWpRAf4ghUgqpQVZw5h9Ry+UfF3hB/aOy6Gc4FmnK+nyr5AkHaWit7rOfKyAg3Fr8Txw9JOn+TpqoomKHPeGaNiVdyk=
