language: java
rvm:
- 2.2
- jruby
- rbx-2
deploy:
  provider: heroku
  api_key:
    secure: grQzEejrRHiZnoJen7Q0zLT+YOIFvYbAxW56/yjySkGCfUtS22VpaLQR+RT66bAPqla9NfTuGUiGVDYQpmuiIy72677ZD+TGXsWBZS+F5P8bRJ+4YdZKH6a5Sjk8npDoyoUzay7kYTpoIAi2mKgNotUkYKDZkXeq7UfknlTC4YBOte7p18OsEJfOL5f4GaIF7494oyiiTYtVR53xp1QN0zyWIeQxrhmF49bMe1Vgu5VSGxD0A0H7Vn/CRKxX+IMSlakcygTSotyn3LaGmzrYuM/I4mNtxw1aoBCJ+CH83q+PAMLQb6zHhfjsE0rVlyFp7CGYeVpuhXMos+3ljbus3RW5+Ty/2WdLear3XG4sMfFR6qIaNjqEzS3eqNrhjn7CfCXzEnSp9AFp2zraYkV4RPkGlc7dJ5pi/4/QWcgHYXYsqoMMXpD3GrRghFvwUOV1olzgd7hDUp6NgfA6kX/wPnfdf8ILu+lEcNI/QggU7HNwrbPxmQLHLXx6m8nIoIB9GluFwzovxnwpnfqU4Q4E+zKYaoVCMDLNDrsUy900bMkXwyfFi6KOMFRwN/i7SSB5coqcTdhXMgV+f13V0Im1QxuRpLpswpmVzP4fq/PkFn+P/hQhDC4urtTLpw9tFTRGk56v/dAYuY1e3orRofO7CIgSlv79Ri5yl/W1rUSzsYo=
