language: java
rvm:
- 2.2
- jruby
- rbx-2
deploy:
  provider: heroku
  api_key:
    secure: rwAiDF2BtZBJvmozGNm660/lkSkDhL5/rYorjhp+EC61Uch0RnJTZLPt/BEVlBPDGmPDcR6Pl2LbnVzCr7vOakVbqgzfJAZHnuJT2GsSlEQCOAnkIP8VVuHJ5VjLdEmbhKk2zW8P6pyi21f5M+hqit8BopK2r74E7n4uYtPqkXBDMabZamlxsM8ULK9ssjDbQiT0mJb0C5TMwWKrADQAC3WdsLlbUWHgQ2/m/UchfSKHd/uvEqesk4fvHGiiw9NA/duUwgexRpIdADkZmEmY9mOU9nfjxXaV8clNAKJ7FB6H4VySf3WeH/gar4jxZAfWZd7L+75vF1o1qebwBJ4DlNsGARe9qEWm0SOuwnZ7d+qciObC8MYkUw0HApp3cr64Z0e+PY8onhomDV2GMNnq5PGfSaOxpE+JUUPwVNINyRFibqGGuCz2XKfTjBNuoFUL7guL4qAfoBS0xlxu110Sc7vVLxCmnsSVOgXxzMJ0c4TIMMkyrcQjrrGmrv8yeIMVdyhjy99B19QwwOhc3cexbXTXFFfQRWlbxG8EFCJWWurI08j0AQbgd2x4IhKFwk+uuNfI2sYb0biGs9+qGm9xxOwF0Nd5qeC7SE3o8QBBEyMfoem26pHGtvIMvCHLtvpGP8ADfdTvBC+JlyvlsQPAwYyhl9Vz3mv3082Zx/H2lHs=
  app: cryptic-temple-51443
  on:
    repo: matthewwilliams-ir/albums-api
